### ISSUE TITLE
Previewer does not show for some users

### ISSUE THREAD

**Issue by chrahunt** [chrahunt/TagProReplays#182]
As reported [here](https://www.reddit.com/r/TagPro/comments/6c9se4/what_does_this_error_mean_in_tpreplays/), some players are receiving `Error loading replay: Cannot read property 'length' of undefined` when trying to preview any of their replays.

The stack trace from the page console:

```
chrome-extension://ejbnakhldlocljfcglmeibhhdnmmcodh/js/content.js:2692 tpr:renderer:error Error loading media:  +784ms TypeError: Cannot read property 'length' of undefined
    at load (chrome-extension://ejbnakhldlocljfcglmeibhhdnmmcodh/js/content.js:3299:40)
    at Array.map (native)
    at load (chrome-extension://ejbnakhldlocljfcglmeibhhdnmmcodh/js/content.js:3300:29)
    at chrome.storage.promise.local.get.then (chrome-extension://ejbnakhldlocljfcglmeibhhdnmmcodh/js/content.js:30447:12)
    at <anonymous>
```

3299 -> `image-promise#load` line 3
3300 -> `image-promise#load` line 4
30447 -> `js/modules/textures.js` line 67

which points to an issue in loading textures. The array we're passing to `loadImage` probably has some `undefined` in it. This implies that `default_textures[something]` is `undefined`, since we don't check it prior to attempting to load the images from the chrome storage.

**Comment by chrahunt** [comment]
With egg ball came a new texture: `egg`. We use `onInstalled` to let us know when the extension is updated, at which point it updates the textures. Since some extensions were disabled due to a permission change (which were reverted yesterday), the Chrome bug [here](https://bugs.chromium.org/p/chromium/issues/detail?id=388231) probably resulted in `onInstalled` not getting called, so `egg` wasn't added.

This was confirmed by a user ([/u/archaelios](https://www.reddit.com/user/archaelios)) with the issue running:

```
chrome.storage.local.get("default_textures", ({default_textures: t}) => console.log(JSON.stringify(Object.keys(t))))
undefined
VM67:1 ["flair","portal","speedpad","speedpadblue","speedpadred","splats","tiles"]
chrome.storage.local.get("default_textures", ({default_textures: t}) => console.log(JSON.stringify(Object.keys(t).filter(k => !t[k]))))
undefined
VM69:1 []
```

in the background page of the extension. The fix (which is probably better anyway) is to reload the textures each extension load regardless. This also avoids the need to specify multiple versions that require a texture reload.
